stages:
 - Static Analysis
 - build



flake8:
  stage: Static Analysis
  tags: ["dev"]
  image: 
    name: python:3.7
  before_script:
  - python3 --version
  - pip install psutil flake8 flake8-polyfill pylint pyparsing
  - pip install -r requirements.txt
  script:
  - flake8 --max-line-length=400 --ignore=F403,F841,F405,F401,E731

build:
  stage: build
  tags: ["dev"]
  image:
    name: docker:19.03.1
  services:
  - docker:19.03.1-dind
  before_script:
  - docker info
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/$CI_PROJECT_PATH .
    - docker tag $CI_REGISTRY/$CI_PROJECT_PATH:latest $CI_REGISTRY/$CI_PROJECT_PATH/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY/$CI_PROJECT_PATH:latest
    - docker push $CI_REGISTRY/$CI_PROJECT_PATH/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHA


